import { Project } from '@/components';

// Images
import SignIn from '@/assets/SignInUpdated.png';
import FPSDungeon from '@/assets/FPSDungeon.png';
import GOL from '@/assets/GOL.png';
import VulkanRenderer from '@/assets/VulkanRenderer.jpg';
import Hoddsmimir from '@/assets/Hoddsmimir.png';
import FlappyBird from '@/assets/FlappyBirdClone.png';
import SteamDreams from '@/assets/steamdreams.jpg';

export default function Projects() {
	return (
		<section className='Projects'>
			<Project
				name='This Site!'
				description='This site itself I wrote to show off and practice my web development skills. I wrote it in TypeScript using Vite and React.'
				year={2025}
				link='/'
			/>
			<Project
				name='STEAM Dreams'
				description='I worked on this game during my internship at Universal Phoenix Group. I worked on a handful of minigames, and systems.'
				year={2025}
				link='https://steamdreams.io/'
				image={SteamDreams}
			/>
			<Project
				name='Sign In System'
				description='A very primitive sign in system I built to learn the basics of full stack. I wrote the the frontend in TypeScript using React, and wrote the backend in Python using Flask. I recently went back and improved the code.'
				year={2024}
				link='https://github.com/Lii02/signin-system'
				image={SignIn}
			/>
			<Project
				name='FPS Dungeon'
				description='This game was made by 2 programmers, though the work was split more in my favor. My work included, but not limited to: level design, turret AI, buy menu, audio engineering, and UI development. It was made in Unity in 4 months, I was also working on my internship at the same time.'
				year={2022}
				link='https://lii02dev.itch.io/fps-dungeon'
				image={FPSDungeon}
			/>
			<Project
				name='Game of Life'
				description="A customizable simulation of Conway's Game Of Life. Writtein in C# using the Windows Forms framework."
				year={2021}
				link='https://github.com/Lii02/ConwayGOL'
				image={GOL}
			/>

			<Project
				name='Vulkan Renderer'
				description='A level renderer with model rendering, texture rendering, and PBR. It uses a custom format generated by a Blender script. Written in C++ using Vulkan for graphics.'
				year={2022}
				link='https://github.com/Lii02/LevelRenderer'
				image={VulkanRenderer}
			/>
			<Project
				name='Hoddsmimir'
				description='This game was made by 5 programmers, with the work split more into 4 of us. My work included, but not limited to: WebGL port, audio, inventory. It was made in Unity in 3 months.'
				year={2021}
				link='https://lii02dev.itch.io/hoddsmimir'
				image={Hoddsmimir}
			/>
			<Project
				name='Flappy Bird Clone'
				description='A simple flappy bird clone I wrote in a day. Written in C++ using SDL2.'
				year={2023}
				link='https://lii02dev.itch.io/flappy-bird-clone'
				image={FlappyBird}
			/>
		</section>
	);
}
